jobs:
  - job: Build
    condition: always()
    displayName: Run Packer
    pool:
      vmImage: ubuntu-16.04
    steps:
      - checkout: self
        clean: true
        persistCredentials: true

      ## Create Build.Version
      - bash: |
          build_version=$(Build.BuildNumber)-$(git rev-parse --short $(Build.SourceVersion))
          echo ${build_version}
          echo "##vso[task.setvariable variable=version;isOutput=true]${build_version}"
        name: buildVersionName
      ## Image Gen using packer
      - bash: |
          packer images/linux/ubuntu1804-tss.json
        name: RunPacker
        displayName: "Run Ubuntu 18.04 TSS Image Generation"
        env:
          ARM_SUBSCRIPTION_ID: $(sp-client-subscription-id)
          ARM_TENANT_ID: ${sp-client-tenant)
          ARM_IMAGE_RESOURCE_GROUP_NAME: $(arm-image-resource-group-name)
          ARM_CLIENT_SECRET: $(sp-client-secret)
          ARM_CLIENT_ID: $(sp-client-id)
          ARM_IMAGE_NAME: $(arm-image-name)