jobs:
  - job: Build
    condition: always()
    displayName: Run Docker
    pool:
      vmImage: ubuntu-16.04
    timeoutInMinutes: 60
    steps:
      - checkout: self
        clean: true
        persistCredentials: true

      ## Create Build.Version
      - bash: |
          build_version=$(Build.BuildNumber)-$(git rev-parse --short $(Build.SourceVersion))
          echo ${build_version}
          echo "##vso[task.setvariable variable=version;isOutput=true]${build_version}"
        name: buildVersionName
      - task: Docker@2
        name: DockerLogin
        inputs:
          command: login
          containerRegistry: $(acr.serviceconnection)
      ## Docker build + push      
      - task: Docker@2
        name: DockerBuildAndPush
        inputs:
          command: buildAndPush
          dockerfile: Dockerfile
          containerRegistry: $(acr.serviceconnection)
          repository: adoagent
          tags: |
            $(buildVersionName.version)
            latest