jobs:
  - job: Build
    condition: always()
    displayName: Run Packer
    pool: EvAnalytics-Pool
    timeoutInMinutes: 240
    steps:
      - checkout: self
        clean: true
        persistCredentials: true

      ## Create Build.Version
      - bash: |
          build_version=$(Build.BuildNumber)-$(git rev-parse --short $(Build.SourceVersion))
          echo ${build_version}
          echo "##vso[task.setvariable variable=version;isOutput=true]${build_version}"
        name: buildVersionName
      ## Download & Install Packer
      - task: AzureCLI@1
        displayName: "Create Resource Group"
        inputs:
          azureSubscription: $(arm-subscription-name)
          arguments: --output none
          scriptLocation: inlineScript
          inlineScript: |
            # Create resource group
            az group create --location $(arm-resource-location) --name $(arm-image-resource-group-name)
      - bash: |
          export VER="1.4.3"
          wget https://releases.hashicorp.com/packer/${VER}/packer_${VER}_linux_amd64.zip
          unzip packer_${VER}_linux_amd64.zip
          sudo mv packer /usr/local/bin
          packer --version
      ## Image Gen using packer
      - bash: |
          packer build images/linux/ubuntu-1604-tss-stripped.json
        name: RunPacker
        displayName: "Run Ubuntu 16.04 TSS Image Generation"
        env:
          ARM_SUBSCRIPTION_ID: $(sp-client-subscription-id)
          ARM_TENANT_ID: $(sp-client-tenant)
          ARM_IMAGE_RESOURCE_GROUP_NAME: $(arm-image-resource-group-name)
          ARM_CLIENT_SECRET: $(sp-client-secret)
          ARM_CLIENT_ID: $(sp-client-id)
          ARM_IMAGE_NAME: $(arm-image-name)
          ARM_RESOURCE_LOCATION: $(arm-resource-location)